### ISSUE TITLE
release下载的使用报错

### ISSUE THREAD

**Issue by citizenll** [focus-creative-games/Excel2TextDiff#1]
已经安装了.net6

![image](https://user-images.githubusercontent.com/16896067/173478911-a7e6a32c-d70c-4bab-b635-3077cdae8c06.png)

![image](https://user-images.githubusercontent.com/16896067/173478990-2b61b2f5-7e34-4b8f-868d-072bdcc23d9a.png)

**Comment by pirunxi** [comment]
Tortoisegit 不在path搜索路径里

**Comment by alpha-xdream** [comment]
要填入Excel2TextDiff\Excel2TextDiff.exe -p TortoiseGitMerge.exe -d %base %mine
